# Generated by Django 6.0.7 on 2026-07-30 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('question', models.TextField()),
                ('category', models.CharField(choices=[('DSA', 'DSA'), ('OOP', 'OOP'), ('DBMS', 'DBMS'), ('OS', 'Operating Systems'), ('CN', 'Computer Networks'), ('SD', 'System Design'), ('HR', 'HR / Behavioral'), ('PROJ', 'Project / Resume')], default='DSA', max_length=10)),
                ('source', models.CharField(choices=[('LeetCode', 'LeetCode'), ('GeeksforGeeks', 'GeeksforGeeks')], default='GeeksforGeeks', max_length=20)),
                ('link', models.URLField(blank=True, max_length=400)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='UserInterviewProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='interview.interviewquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
