# Generated by Django 6.0.7 on 2026-07-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='topic',
            field=models.CharField(default='Arrays', help_text='DSA pattern/topic this question belongs to', max_length=60),
        ),
    ]
