# Generated by Django 6.0.7 on 2026-07-30 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(unique=True)),
                ('domain', models.CharField(choices=[('OOP', 'Object Oriented Programming'), ('DBMS', 'DBMS'), ('OS', 'Operating Systems'), ('CN', 'Computer Networks'), ('SE', 'Software Engineering'), ('SD', 'System Design')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Basic', max_length=15)),
                ('explanation', models.TextField()),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TechQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(choices=[('OOP', 'Object Oriented Programming'), ('DBMS', 'DBMS'), ('OS', 'Operating Systems'), ('CN', 'Computer Networks'), ('SE', 'Software Engineering'), ('SD', 'System Design')], max_length=10)),
                ('question', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('source', models.CharField(choices=[('LeetCode', 'LeetCode'), ('GeeksforGeeks', 'GeeksforGeeks')], default='GeeksforGeeks', max_length=20)),
                ('link', models.URLField(max_length=400)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['domain', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserTechProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='technical.techquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tech_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
