# Generated by Django 6.0.7 on 2026-07-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='example',
            field=models.TextField(blank=True, default='', help_text='Concrete example or interview-style follow-up illustrating the concept'),
        ),
    ]
