# Generated by Django 6.0.6 on 2026-07-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technical', '0003_concept_reference_flowchart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='flowchart_mermaid',
            field=models.TextField(blank=True, default='', help_text='Mermaid.js flowchart definition rendered on the concept page'),
        ),
        migrations.AlterField(
            model_name='concept',
            name='reference_url',
            field=models.URLField(blank=True, default='', help_text='Direct link to the real GeeksforGeeks article for this concept', max_length=400),
        ),
    ]
