# Generated by Django 6.0.7 on 2026-07-30 05:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('source', models.CharField(choices=[('LeetCode', 'LeetCode'), ('GeeksforGeeks', 'GeeksforGeeks')], default='LeetCode', max_length=20)),
                ('link', models.URLField(max_length=400)),
                ('order', models.PositiveIntegerField(default=0)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='dsa.pattern')),
            ],
            options={
                'ordering': ['pattern__order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='UserQuestionProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='dsa.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsa_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'question')},
            },
        ),
    ]
